version: '3.8'
services:
  os-node:
    container_name: so-node
    build: .
    # ESTO ES CRUCIAL: Hace que el contenedor use la IP real de la EC2
    network_mode: "host"
    volumes:
      - .:/opt/os-decentralized
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
