version: '3.8'

services:
  os-node:
    build: .
    image: so-descentralizado:latest
    container_name: so-node
    network_mode: "host"
    environment:
      - NODE_ID=${NODE_ID}
      - NODE_IP=${NODE_IP}
    volumes:
      - ./logs:/opt/os-decentralized/logs
    restart: unless-stopped
